server:
  port: 8081

spring:
  application:
    name: dubbo-sample-provider

demo:
  service:
    version: 1.0.0

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  protocol:
    name: dubbo
    port: -1
